package graficos;

import graficos.acciones.AbreNavegador;
import graficos.acciones.EnviaCoordenadas;
import graficos.dialogos.DialogoInformacion;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.SwingUtilities;
import java.awt.Frame;
import java.awt.Graphics;

import javax.swing.event.ChangeListener;
import javax.swing.event.ChangeEvent;

/**
 * Interfaz gráfica.
 * @author Omar
 */
public class grafico extends javax.swing.JPanel {
	
	public void closeConnection() {
		//enviaCoordenadas.releaseConnector();
	}

    /**
     * Creates new form grafico
     */
    public grafico() {
        initComponents();
        
        enviaCoordenadas = new EnviaCoordenadas();
        //enviaCoordenadas.initConnector();
        
        panelRadar.addMouseListener(enviaCoordenadas);
        
        sliderZoom.addChangeListener(new ChangeListener() {
        	public void stateChanged(ChangeEvent e) {
        		enviaCoordenadas.setZoom(sliderZoom.getValue());
        	}
        });
        
        sliderSpeed.addChangeListener(new ChangeListener() {
        	public void stateChanged(ChangeEvent e) {
        		enviaCoordenadas.setSpeed(sliderSpeed.getValue());
        	}
        });
        
        sliderAngularSpeed.addChangeListener(new ChangeListener() {
        	public void stateChanged(ChangeEvent e) {
        		enviaCoordenadas.setAngularSpeed(sliderAngularSpeed.getValue());
        	}
        });
        
        infoLink.addMouseListener(new MouseAdapter(){
        	public void mouseClicked(MouseEvent e) {
        		DialogoInformacion d = new DialogoInformacion((Frame) SwingUtilities.getRoot(getGrafico()), true);
        		d.setVisible(true);
        	}
        });
        
        legoLink.addMouseListener(new AbreNavegador("http://mindstorms.lego.com/en-us/whatisnxt/default.aspx"));
        
        nasaLink.addMouseListener(new AbreNavegador("http://spaceappschallenge.org/project/mexillego/"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        legoLink1 = new javax.swing.JPanel();
        nasaLink1 = new javax.swing.JPanel();
        panelRadar = new Imagen("recursos/imagenes/Desktop/DesktopRadar.png");
        sliderZoom = new javax.swing.JSlider();
        sliderSpeed = new javax.swing.JSlider();
        sliderAngularSpeed = new javax.swing.JSlider();
        infoLink = new Imagen("recursos/imagenes/icon_info35px.png");
        configLink = new Imagen("recursos/imagenes/home-settings-cog.png");
        nasaLink = new Imagen("recursos/imagenes/Icon-Nasa-Small.png");
        legoLink = new Imagen("recursos/imagenes/iconoLegoSmall.png");
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        legoLink1.setMinimumSize(new java.awt.Dimension(70, 70));

        javax.swing.GroupLayout legoLink1Layout = new javax.swing.GroupLayout(legoLink1);
        legoLink1.setLayout(legoLink1Layout);
        legoLink1Layout.setHorizontalGroup(
            legoLink1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        legoLink1Layout.setVerticalGroup(
            legoLink1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        nasaLink1.setMinimumSize(new java.awt.Dimension(70, 70));

        javax.swing.GroupLayout nasaLink1Layout = new javax.swing.GroupLayout(nasaLink1);
        nasaLink1.setLayout(nasaLink1Layout);
        nasaLink1Layout.setHorizontalGroup(
            nasaLink1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        nasaLink1Layout.setVerticalGroup(
            nasaLink1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        //setBackground(new java.awt.Color(1, 1, 1));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(750, 550));

        panelRadar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 102, 0)));
        panelRadar.setForeground(new java.awt.Color(102, 0, 153));

        javax.swing.GroupLayout panelRadarLayout = new javax.swing.GroupLayout(panelRadar);
        panelRadar.setLayout(panelRadarLayout);
        panelRadarLayout.setHorizontalGroup(
            panelRadarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        panelRadarLayout.setVerticalGroup(
            panelRadarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        sliderZoom.setBackground(new java.awt.Color(1, 1, 1));
        sliderZoom.setForeground(new java.awt.Color(255,255,255));
        sliderZoom.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        sliderZoom.setMajorTickSpacing(Constants.ZOOM_STEP);
        sliderZoom.setMaximum(Constants.ZOOM_MAX);
        sliderZoom.setMinimum(Constants.ZOOM_MIN);
        sliderZoom.setOrientation(javax.swing.JSlider.VERTICAL);
        sliderZoom.setPaintTicks(true);
        sliderZoom.setSnapToTicks(true);
        sliderZoom.setValue(Constants.ZOOM_DEFAULT);
        sliderZoom.setOpaque(false);

        sliderSpeed.setBackground(new java.awt.Color(1, 1, 1));
        sliderSpeed.setForeground(new java.awt.Color(255,255,255));
        sliderSpeed.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        sliderSpeed.setMajorTickSpacing(Constants.SPEED_STEP);
        sliderSpeed.setMaximum(Constants.SPEED_MAX);
        sliderSpeed.setMinimum(Constants.SPEED_MIN);
        sliderSpeed.setOrientation(javax.swing.JSlider.VERTICAL);
        sliderSpeed.setPaintTicks(true);
        sliderSpeed.setSnapToTicks(true);
        sliderSpeed.setToolTipText("");
        sliderSpeed.setValue(Constants.SPEED_DEFAULT);
        sliderSpeed.setOpaque(false);

        sliderAngularSpeed.setBackground(new java.awt.Color(1, 1, 1));
        sliderAngularSpeed.setForeground(new java.awt.Color(255,255,255));
        sliderAngularSpeed.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        sliderAngularSpeed.setMajorTickSpacing(Constants.SPEED_STEP);
        sliderAngularSpeed.setMaximum(Constants.SPEED_MAX);
        sliderAngularSpeed.setMinimum(Constants.SPEED_MIN);
        sliderAngularSpeed.setOrientation(javax.swing.JSlider.VERTICAL);
        sliderAngularSpeed.setPaintTicks(true);
        sliderAngularSpeed.setSnapToTicks(true);
        sliderAngularSpeed.setValue(Constants.SPEED_DEFAULT);
        sliderAngularSpeed.setOpaque(false);

        infoLink.setMinimumSize(new java.awt.Dimension(70, 70));

        javax.swing.GroupLayout infoLinkLayout = new javax.swing.GroupLayout(infoLink);
        infoLink.setLayout(infoLinkLayout);
        infoLinkLayout.setHorizontalGroup(
            infoLinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        infoLinkLayout.setVerticalGroup(
            infoLinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        configLink.setToolTipText("");
        configLink.setMinimumSize(new java.awt.Dimension(70, 70));

        javax.swing.GroupLayout configLinkLayout = new javax.swing.GroupLayout(configLink);
        configLink.setLayout(configLinkLayout);
        configLinkLayout.setHorizontalGroup(
            configLinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        configLinkLayout.setVerticalGroup(
            configLinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        nasaLink.setMinimumSize(new java.awt.Dimension(70, 70));

        javax.swing.GroupLayout nasaLinkLayout = new javax.swing.GroupLayout(nasaLink);
        nasaLink.setLayout(nasaLinkLayout);
        nasaLinkLayout.setHorizontalGroup(
            nasaLinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        nasaLinkLayout.setVerticalGroup(
            nasaLinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        legoLink.setMinimumSize(new java.awt.Dimension(70, 70));

        javax.swing.GroupLayout legoLinkLayout = new javax.swing.GroupLayout(legoLink);
        legoLink.setLayout(legoLinkLayout);
        legoLinkLayout.setHorizontalGroup(
            legoLinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        legoLinkLayout.setVerticalGroup(
            legoLinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jLabel1.setBackground(new java.awt.Color(1, 1, 1));
        jLabel1.setForeground(new java.awt.Color(255,255,255));
        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel1.setText("Zoom");
        jLabel1.setOpaque(false);

        jLabel2.setBackground(new java.awt.Color(1, 1, 1));
        jLabel2.setForeground(new java.awt.Color(255,255,255));
        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel2.setText("Linear");
        jLabel2.setOpaque(false);

        jLabel3.setBackground(new java.awt.Color(1, 1, 1));
        jLabel3.setForeground(new java.awt.Color(255,255,255));
        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel3.setText("Angular");
        jLabel3.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sliderZoom, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sliderSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(sliderAngularSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(panelRadar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nasaLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(legoLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 505, Short.MAX_VALUE)
                        .addComponent(configLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(infoLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nasaLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(legoLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(configLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRadar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sliderAngularSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sliderZoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sliderSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel configLink;
    private javax.swing.JPanel infoLink;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel legoLink;
    private javax.swing.JPanel legoLink1;
    private javax.swing.JPanel nasaLink;
    private javax.swing.JPanel nasaLink1;
    private javax.swing.JPanel panelRadar;
    private javax.swing.JSlider sliderAngularSpeed;
    private javax.swing.JSlider sliderSpeed;
    private javax.swing.JSlider sliderZoom;
    // End of variables declaration//GEN-END:variables
    
    private EnviaCoordenadas enviaCoordenadas;
    
    private grafico getGrafico() {
    	return this;
    }
}
